[domaincontrollers]
dc01  ansible_host=192.168.56.10  ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key
dc02  ansible_host=192.168.56.102  ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key

[workstations]
wkstn01 ansible_host=192.168.56.20  ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key

[siem]
siem01  ansible_host=192.168.56.50  ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key

[ticketing]
ticket01 ansible_host=192.168.56.105 ansible_user=labadmin ansible_ssh_private_key_file=~/.ssh/lab_key

[lab:children]
domaincontrollers
workstations
siem
ticketing

[lab:vars]
ansible_python_interpreter=/usr/bin/python3
