[domain_controllers]
dc01 ansible_host=10.0.0.10 ansible_user=Administrator ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_scheme=http ansible_winrm_operation_timeout_sec=120 ansible_winrm_read_timeout_sec=150
dc02 ansible_host=10.0.0.11 ansible_user=Administrator ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_scheme=http ansible_winrm_operation_timeout_sec=120 ansible_winrm_read_timeout_sec=150

[workstations]
wkstn01 ansible_host=10.0.0.20 ansible_user=labuser ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_scheme=http ansible_winrm_operation_timeout_sec=120 ansible_winrm_read_timeout_sec=150

[siem]
siem01 ansible_host=10.0.0.50 ansible_user=labadmin ansible_connection=ssh ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[lab:children]
domain_controllers
workstations
siem
